name: hideck-image-build

services:
  hideck:
    image: yibaiba/hideck:${HIDECK_VERSION:-2.1.22}
    build:
      context: .
      dockerfile: Dockerfile.release
      pull: true
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        VERSION: v${HIDECK_VERSION:-2.1.22}
        REVISION: ${HIDECK_REVISION:?HIDECK_REVISION is required}
        BUILDTIME: ${HIDECK_BUILDTIME:?HIDECK_BUILDTIME is required}
      tags:
        - yibaiba/hideck:${HIDECK_MINOR_VERSION:-2.1}
        - yibaiba/hideck:${HIDECK_LATEST_TAG:-latest}
      provenance: false
      sbom: false
